# Workflow for test and build.
name: Build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: windows-latest

    env:
      solution: Argos.Framework.ServiceInjector.sln
      test_project: Argos.Framework.ServiceInjector.Tests\Argos.Framework.ServiceInjector.Tests.csproj
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Execute unit tests
      run: dotnet test $env:test_project
    
    - name: Build project
      run: dotnet build $env:solution --configuration Release
